// <auto-generated/>
// This file uses Nerdbank.GitVersioning's generated ThisAssembly class.
// Version is automatically read from version.json at compile time.

namespace MicroEngine.Core.Engine;

/// <summary>
/// Provides engine version and metadata information.
/// </summary>
/// <remarks>
/// This class wraps Nerdbank.GitVersioning's ThisAssembly for public API.
/// Version is automatically generated from version.json during build.
/// </remarks>
public static class EngineInfo
{
    /// <summary>
    /// Gets the full engine version string (e.g., "0.7.0-alpha").
    /// </summary>
    public static string VERSION => ParseVersion(ThisAssembly.AssemblyInformationalVersion);

    /// <summary>
    /// Gets the major version number.
    /// </summary>
    public static int MAJOR => ParseMajor(VERSION);

    /// <summary>
    /// Gets the minor version number.
    /// </summary>
    public static int MINOR => ParseMinor(VERSION);

    /// <summary>
    /// Gets the patch version number.
    /// </summary>
    public static int PATCH => ParsePatch(VERSION);

    /// <summary>
    /// Gets the pre-release label (e.g., "alpha", "beta", "rc1"), or empty string for stable releases.
    /// </summary>
    public static string PRE_RELEASE => ParsePreRelease(VERSION);

    /// <summary>
    /// Gets the engine name.
    /// </summary>
    public const string NAME = "MicroEngine";

    /// <summary>
    /// Gets the full display name with version (e.g., "MicroEngine v0.7.0-alpha").
    /// </summary>
    public static string FullName => $"{NAME} v{VERSION}";

    /// <summary>
    /// Gets the semantic version in numeric format (e.g., "0.7.0").
    /// </summary>
    public static string SemanticVersion => $"{MAJOR}.{MINOR}.{PATCH}";

    /// <summary>
    /// Determines whether this is a pre-release version.
    /// </summary>
    public static bool IsPreRelease => ThisAssembly.IsPrerelease;

    /// <summary>
    /// Determines whether this is a stable release version.
    /// </summary>
    public static bool IsStable => !IsPreRelease;

    /// <summary>
    /// Gets the Git commit ID (SHA).
    /// </summary>
    public static string GitCommitId => ThisAssembly.GitCommitId;

    /// <summary>
    /// Gets the Git commit date.
    /// </summary>
    public static DateTime GitCommitDate => ThisAssembly.GitCommitDate;

    // Helper methods to parse version string
    private static string ParseVersion(string informationalVersion)
    {
        // Format: "0.7.0.4-alpha+1ab64f76f8"
        // Extract: "0.7.0-alpha"
        var parts = informationalVersion.Split('+')[0]; // Remove commit hash
        var versionParts = parts.Split('.');
        
        if (versionParts.Length >= 3)
        {
            var baseVersion = $"{versionParts[0]}.{versionParts[1]}.{versionParts[2]}";
            var preReleasePart = parts.Contains('-') ? parts.Substring(parts.IndexOf('-')) : "";
            return baseVersion + preReleasePart;
        }
        
        return parts;
    }

    private static int ParseMajor(string version)
    {
        var parts = version.Split('-')[0].Split('.');
        return parts.Length > 0 && int.TryParse(parts[0], out var major) ? major : 0;
    }

    private static int ParseMinor(string version)
    {
        var parts = version.Split('-')[0].Split('.');
        return parts.Length > 1 && int.TryParse(parts[1], out var minor) ? minor : 0;
    }

    private static int ParsePatch(string version)
    {
        var parts = version.Split('-')[0].Split('.');
        return parts.Length > 2 && int.TryParse(parts[2], out var patch) ? patch : 0;
    }

    private static string ParsePreRelease(string version)
    {
        var parts = version.Split('-', 2);
        return parts.Length > 1 ? parts[1] : "";
    }
}